# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d85cdf5331b40442f1814abf20f128f803765adae70916bd944dba753af57bdafed4a0c61936c53bda8491fb019628879bd55c18bf73466b0ed335cf936db486

test:
  secret_key_base: 8d49f8eebf8a6a2a518c4c00897e2992c1161c825bec68714251db836f52926131205642c8ba2779874b090e823dcc120553462546018682f250ad12a4ec1901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
